# Generated by Django 4.2.9 on 2024-02-17 07:32

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_alter_pricingtier_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingtier",
            name="features",
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="pricing_features",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="+", to="pricing.pricingfeature"
            ),
        ),
    ]
