# Generated by Django 4.2.9 on 2024-02-16 15:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon such as bx-world",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=100, null=True)),
                ("subheading", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="wagtailcore.page",
                    ),
                ),
            ],
        ),
    ]
