# Generated by Django 4.2.9 on 2024-02-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="subheading",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="heading",
            new_name="title",
        ),
    ]
