# Generated by Django 4.2.9 on 2024-02-16 16:03

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_homepage_about_list_four_and_more"),
        ("services", "0002_rename_subheading_service_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="home.homepage",
            ),
        ),
    ]
