# Generated by Django 4.2.9 on 2024-02-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("services", "0004_service_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Enter a brief description of the service.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text='Enter the icon code for this service. This field uses Boxicons, and you can find a variety of icons with the class "bx". For example, use "bx-world" for a world icon. Leave it blank if no icon is needed.',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page to link to when users interact with this service.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Provide a title for the service",
                max_length=100,
                null=True,
            ),
        ),
    ]
