# Generated by Django 4.2.9 on 2024-02-19 04:58

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="posts", to="blog.category"
            ),
        ),
    ]
