# Generated by Django 4.2.9 on 2024-02-21 08:24

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_bloglisting_image_alter_author_job_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bloglisting",
            options={
                "verbose_name": "Blog Listing",
                "verbose_name_plural": "Blog Listings",
            },
        ),
        migrations.AlterModelOptions(
            name="blogpage",
            options={"verbose_name": "Blogpage", "verbose_name_plural": "Blogpages"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="bloglisting",
            name="subheading",
        ),
        migrations.AddField(
            model_name="bloglisting",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text="This text serves as a brief introduction or overview for the blog listing page. It may provide context or a summary of the content featured on this page.",
                verbose_name="Introduction Text",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Optionally, provide a brief biography or description of the author.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                help_text="Optionally, enter the Facebook URL of the author.",
                null=True,
                verbose_name="Facebook URL",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(
                help_text="Enter the first name of the author",
                max_length=254,
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                help_text=" Optionally, enter the Instagram URL of the author.",
                null=True,
                verbose_name="Instagram URL",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="Optionally, provide the job title of the author.",
                max_length=254,
                null=True,
                verbose_name="Job Title",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(
                help_text="Enter the last name of the author.",
                max_length=254,
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="twitter_url",
            field=models.URLField(
                blank=True,
                help_text="Optionally, enter the Twitter URL of the author.",
                null=True,
                verbose_name="X URL",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Select categories that best describe the content of the post.",
                related_name="posts",
                to="blog.category",
                verbose_name="Categories",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Enter a unique name for the category. Categories are used to classify and organize blog posts. Choose a descriptive name that reflects the content associated with this category.",
                max_length=255,
                unique=True,
                verbose_name="Category Name",
            ),
        ),
    ]
