# Generated by Django 4.2.9 on 2024-02-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Page to link to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_text",
            field=models.CharField(
                blank=True,
                help_text="Text to display on CTA Button",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="heading",
            field=models.CharField(
                blank=True,
                help_text="Heading that describes the business",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subheading",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="welcome_text",
            field=models.CharField(
                blank=True, help_text="Welcome to Striker", max_length=255, null=True
            ),
        ),
    ]
