# Generated by Django 4.2.9 on 2024-02-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_heading_homepage_hero_heading_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="body",
            new_name="about_body",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="cta_link",
            new_name="about_cta_link",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="cta_text",
            new_name="about_cta_text",
        ),
    ]
