# Generated by Django 4.2.9 on 2024-02-16 15:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_homepage_services_heading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about_list_four",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_list_one",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_list_three",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_list_two",
        ),
        migrations.CreateModel(
            name="AboutList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_listed_services",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
    ]
