# Generated by Django 4.2.9 on 2024-02-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0008_remove_homepage_about_list_four_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_descr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_title",
            field=models.CharField(
                blank=True,
                help_text="Such as Call to Action",
                max_length=100,
                null=True,
            ),
        ),
    ]
