# Generated by Django 4.2.9 on 2024-02-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_standardpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="scrollto_link",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Scroll To Link"
            ),
        ),
    ]
