# Generated by Django 4.2.9 on 2024-02-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_standardpage_scrollto_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardpage",
            name="scrollto_link",
        ),
    ]
