# Generated by Django 4.2.9 on 2024-02-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_genericsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "links_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "services_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "subscribe_email_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "subscribe_email_body",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
