# Generated by Django 4.2.9 on 2024-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_standardpage_body_standardpage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
    ]
