# Generated by Django 4.2.9 on 2024-02-21 08:54

from django.db import migrations, models
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_formpage_introduction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="standardpage",
            name="image",
        ),
        migrations.AddField(
            model_name="formpage",
            name="subheading",
            field=models.TextField(
                blank=True,
                help_text="Provide a subheading for this section, offering additional context or information to users. Leave it blank if not needed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select a header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            features=["bold", "italic", "link"],
                            icon="pilcrow",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="e.g. Marvin Paul",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Insert an embed URL",
                            icon="media",
                            template="blocks/embed_block.html",
                        ),
                    ),
                ],
                help_text="Compose the main content for this form page using various content blocks.",
                use_json_field=True,
                verbose_name="Page Body",
            ),
        ),
        migrations.AlterField(
            model_name="formpage",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text=" Provide a brief introduction or overview for this form page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formpage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Customize the message displayed to users after submitting the form.",
                verbose_name="Thank You Text",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select a header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            features=["bold", "italic", "link"],
                            icon="pilcrow",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="e.g. Marvin Paul",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Insert an embed URL",
                            icon="media",
                            template="blocks/embed_block.html",
                        ),
                    ),
                ],
                blank=True,
                help_text="Compose the main content for this page. Utilize various content blocks to structure and format the information effectively.",
                use_json_field=True,
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text="Provide a brief introduction or overview for this page.",
                null=True,
            ),
        ),
    ]
