# Generated by Django 4.2.9 on 2024-02-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_remove_formpage_image_remove_standardpage_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footerinfo",
            options={
                "verbose_name": "Footer Information",
                "verbose_name_plural": "Footer Information",
            },
        ),
        migrations.RemoveField(
            model_name="formpage",
            name="subheading",
        ),
        migrations.AlterField(
            model_name="footerinfo",
            name="links_title",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Enter a title for the links section in the footer.",
            ),
        ),
        migrations.AlterField(
            model_name="footerinfo",
            name="services_title",
            field=models.CharField(
                blank=True,
                help_text="Enter a title for the services section in the footer.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="footerinfo",
            name="subscribe_email_body",
            field=models.CharField(
                blank=True,
                help_text="Enter the text or body content for the email subscription section in the footer.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="footerinfo",
            name="subscribe_email_title",
            field=models.CharField(
                blank=True,
                help_text="Enter a title for the email subscription section in the footer.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="email",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contact Email"
            ),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="facebook_url",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook URL"),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="instagram_url",
            field=models.URLField(blank=True, null=True, verbose_name="Instagram URL"),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True, verbose_name="LinkedIn URL"),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="phone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contact Phone"
            ),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="telegram_url",
            field=models.URLField(blank=True, null=True, verbose_name="Telegram URL"),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="tiktok_url",
            field=models.URLField(blank=True, null=True, verbose_name="Tiktok URL"),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="twitter_url",
            field=models.URLField(blank=True, null=True, verbose_name="Twitter URL"),
        ),
        migrations.AlterField(
            model_name="genericsettings",
            name="whatsapp_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="WhatsApp Business URL"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.CharField(
                default="Buzzy",
                help_text="Enter the text for the website's logo. This is the displayed logo text.",
                max_length=20,
                verbose_name="Logo Text",
            ),
        ),
    ]
