# Generated by Django 4.2.9 on 2024-02-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("base", "0010_alter_footerinfo_options_remove_formpage_subheading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="branding_favicon",
            field=models.ForeignKey(
                blank=True,
                help_text="Upload an image (png or ico) to be used as the website favicon. This image will appear in the browser tab.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Favicon",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="branding_login",
            field=models.CharField(
                blank=True,
                default="Sign in to FlexiSite",
                help_text='Enter the text to be displayed on the login page. If left blank, the default is "Sign in to FlexiSite."',
                max_length=100,
                null=True,
                verbose_name="Login Text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="branding_title",
            field=models.CharField(
                blank=True,
                default="FlexiSite",
                help_text='Enter the title to be displayed in the title tag of the website. If left blank, the default value is "FlexiSite."',
                max_length=50,
                null=True,
                verbose_name="Site Title",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="branding_welcome",
            field=models.CharField(
                blank=True,
                default="Welcome to FlexiSite CMS",
                help_text='Enter the welcome text to be displayed on the admin home page. If left blank, the default is "Welcome to FlexiSite CMS."',
                max_length=100,
                null=True,
                verbose_name="Welcome Text",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.CharField(
                default="FlexiSite",
                help_text="Enter the text or name for the site logo. This text will be displayed as the logo in the header and footer.",
                max_length=20,
                verbose_name="Site Logo",
            ),
        ),
    ]
